# Generated by Django 5.2.8 on 2025-11-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioncorrelation",
            name="question_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correlation_a",
                to="surveys.question",
            ),
        ),
        migrations.AddField(
            model_name="questioncorrelation",
            name="question_b",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correlation_b",
                to="surveys.question",
            ),
        ),
        migrations.AddField(
            model_name="questioncorrelation",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.survey"
            ),
        ),
        migrations.AddField(
            model_name="surveyanalyticssnapshot",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_snapshots",
                to="surveys.survey",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questioncorrelation",
            unique_together={("survey", "question_a", "question_b")},
        ),
    ]
