# Generated by Django 5.2 on 2025-11-23 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0003_initial"),
        ("surveys", "0004_remove_survey_vote_limit_per_device"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="surveyresponse",
            unique_together={("survey", "user")},
        ),
        migrations.DeleteModel(
            name="VoteThrottleLog",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="device_fingerprint",
        ),
    ]
