# Generated by Django 5.2 on 2025-11-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0003_seed_templates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="vote_limit_per_device",
        ),
    ]
