# Generated by Django 5.2.8 on 2025-11-17 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Один вариант"),
                            ("multiple", "Несколько вариантов"),
                            ("text", "Текст"),
                            ("rating", "Рейтинг 1-5"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("max_text_length", models.PositiveIntegerField(default=1000)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "survey_type",
                    models.CharField(
                        choices=[("anonymous", "Анонимный"), ("public", "Публичный")],
                        default="anonymous",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активный"),
                            ("closed", "Закрыт"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vote_limit_per_device",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_template_based", models.BooleanField(default=False)),
                ("theme", models.CharField(default="light", max_length=50)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="survey_logos/"),
                ),
                ("welcome_message", models.CharField(blank=True, max_length=255)),
                ("thank_you_message", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("satisfaction", "Оценка удовлетворенности"),
                            ("marketing", "Маркетинговое исследование"),
                            ("education", "Образовательный тест"),
                            ("feedback", "Обратная связь о мероприятии"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="surveys.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
