# Generated by Django 5.2.8 on 2025-11-17 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("responses", "0001_initial"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="surveys.question"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="selected_choices",
            field=models.ManyToManyField(blank=True, to="surveys.choice"),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="surveys.survey",
            ),
        ),
    ]
